apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-python
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/serverless-demo/python-api-create:0.1
          env:
            - name: TARGET
              value: "Python Sample v1"
            - name: DBHOST
              value: "serverless-demo-pg"
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: serverless-demo-pg-hippo-secret
                  key: username
            - name: DBPASS
              valueFrom:
                secretKeyRef:
                  name: serverless-demo-pg-hippo-secret
                  key: password