apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-python
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/serverless-demo/serverless-demo-git
          env:
            - name: TARGET
              value: "Python Sample v1"