apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api-create
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api-create
        app.kubernetes.io/instance: api-create
        app.kubernetes.io/name: api-create
        app.kubernetes.io/part-of: serverless-demo-backend
        app.openshift.io/runtime: python
      annotations:
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/targetUtilizationPercentage: "80"
    spec:
      containers:
      - env:
          - name: DB
            valueFrom:
              secretKeyRef:
                key: dbname
                name: serverless-demo-pg-pguser-hippo
          - name: DBHOST
            valueFrom:
              secretKeyRef:
                key: host
                name: serverless-demo-pg-pguser-hippo
          - name: DBUSER
            valueFrom:
              secretKeyRef:
                key: user
                name: serverless-demo-pg-pguser-hippo
          - name: DBPASS
            valueFrom:
              secretKeyRef:
                key: password
                name: serverless-demo-pg-pguser-hippo
        image: image-registry.openshift-image-registry.svc:5000/serverless-demo/python-api-create:1.1
        imagePullPolicy: IfNotPresent
        name: user-container
        ports:
        - containerPort: 8080
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100