apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: s2i-python-api-create-
spec:
  params:
    - name: IMAGE
      value: 'python-api-create:0.51'
    - name: SRCDIR
      value: backend/create/src
    - name: KNSERVICE
      value: "api-create"
  pipelineRef:
    name: build-python-backend
  serviceAccountName: pipeline
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi