apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-python-backend
spec:
  params:
  - description: the name of the image
    name: IMAGE
    type: string
  - description: source directory
    name: SRCDIR
    type: string
  - description: the kn service to update
    name: KNSERVICE
    type: string
  workspaces:
    - name: shared-workspace
    - name: sslcertdir
      optional: true
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/ccdgrundhoefer/serverless-demo.git
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "master"
    - name: s2i
      taskRef:
        name: s2i-python
        kind: ClusterTask
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: TLSVERIFY
          value: "false"
        - name: PATH_CONTEXT
          value: "$(params.SRCDIR)"
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.IMAGE)
    - name: kn-update-image
      taskRef:
        name: kn
        kind: ClusterTask
      timeout: "5m"
      runAfter:
        - s2i
      params:
        - name: ARGS
          value: 
          - "service"
          - "update"
          - "$(params.KNSERVICE)"
          - "--image"
          - "image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.IMAGE)"