apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: s2i-python-hello-world
spec:
  params:
    - name: IMAGE
      value: 'python-hello-world:1'
    - name: SRCDIR
      value: backend/create/src
  pipelineRef:
    name: build-python-backend
  serviceAccountName: pipeline
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi